
package src;


public class BankJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BankJFrame.class.getName());
    
    //  CreateObject
    Queue withdraw_deposit = new Queue(6);
    Queue loan = new Queue(6);
    Queue newacc = new Queue(6);
    
    
    public BankJFrame() {
        initComponents();
        
        getContentPane().setPreferredSize(new java.awt.Dimension(1000, 580));
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);
        
        initButtonStates();
    }
    
    private void initButtonStates() {
        callQueue_Counter1.setEnabled(false);
        callQueue_Counter2.setEnabled(false);
        callQueue_Counter3.setEnabled(false);
        finishQueue_Counter1.setEnabled(false);
        finishQueue_Counter2.setEnabled(false);
        finishQueue_Counter3.setEnabled(false);

        callQueue_counter4.setEnabled(false);
        finishQueue_counter4.setEnabled(false);

        callQueue_counter5.setEnabled(false);
        finishQueue_counter5.setEnabled(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Withdraw_Deposit = new javax.swing.JButton();
        Loan = new javax.swing.JButton();
        new_Account = new javax.swing.JButton();
        NameCounter1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background_counter1_2_3 = new javax.swing.JPanel();
        callQueue_Counter1 = new javax.swing.JButton();
        callQueue_Counter2 = new javax.swing.JButton();
        callQueue_Counter3 = new javax.swing.JButton();
        Divider_1 = new javax.swing.JPanel();
        Divider_2 = new javax.swing.JPanel();
        finishQueue_Counter1 = new javax.swing.JButton();
        finishQueue_Counter2 = new javax.swing.JButton();
        finishQueue_Counter3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Divider_3 = new javax.swing.JPanel();
        background_counter3_4 = new javax.swing.JPanel();
        callQueue_counter4 = new javax.swing.JButton();
        callQueue_counter5 = new javax.swing.JButton();
        finishQueue_counter4 = new javax.swing.JButton();
        finishQueue_counter5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        loanLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        bank_Map = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        Withdraw_Deposit.setBackground(new java.awt.Color(255, 204, 204));
        Withdraw_Deposit.setText("Withdraw_Deposit");
        Withdraw_Deposit.addActionListener(this::Withdraw_DepositActionPerformed);

        Loan.setBackground(new java.awt.Color(255, 204, 204));
        Loan.setText("Loan");
        Loan.addActionListener(this::LoanActionPerformed);

        new_Account.setBackground(new java.awt.Color(204, 255, 204));
        new_Account.setText("new Account");
        new_Account.addActionListener(this::new_AccountActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(new_Account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Loan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Withdraw_Deposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Withdraw_Deposit)
                .addGap(18, 18, 18)
                .addComponent(Loan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(new_Account, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 140, 140));

        NameCounter1.setForeground(new java.awt.Color(255, 255, 255));
        NameCounter1.setText("Deposit-withdraw 1");
        getContentPane().add(NameCounter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 120, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Deposit-withdraw2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 130, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Deposit-withdraw3");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 110, 30));

        background_counter1_2_3.setBackground(new java.awt.Color(255, 255, 204));
        background_counter1_2_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        callQueue_Counter1.setBackground(new java.awt.Color(153, 255, 255));
        callQueue_Counter1.setText("Call Queue");
        callQueue_Counter1.addActionListener(this::callQueue_Counter1ActionPerformed);

        callQueue_Counter2.setBackground(new java.awt.Color(153, 255, 255));
        callQueue_Counter2.setText("Call Queue");
        callQueue_Counter2.addActionListener(this::callQueue_Counter2ActionPerformed);

        callQueue_Counter3.setBackground(new java.awt.Color(153, 255, 255));
        callQueue_Counter3.setText("Call Queue");
        callQueue_Counter3.addActionListener(this::callQueue_Counter3ActionPerformed);

        Divider_1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout Divider_1Layout = new javax.swing.GroupLayout(Divider_1);
        Divider_1.setLayout(Divider_1Layout);
        Divider_1Layout.setHorizontalGroup(
            Divider_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        Divider_1Layout.setVerticalGroup(
            Divider_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );

        Divider_2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout Divider_2Layout = new javax.swing.GroupLayout(Divider_2);
        Divider_2.setLayout(Divider_2Layout);
        Divider_2Layout.setHorizontalGroup(
            Divider_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        Divider_2Layout.setVerticalGroup(
            Divider_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        finishQueue_Counter1.setBackground(new java.awt.Color(153, 255, 153));
        finishQueue_Counter1.setText("Finish");
        finishQueue_Counter1.addActionListener(this::finishQueue_Counter1ActionPerformed);

        finishQueue_Counter2.setBackground(new java.awt.Color(153, 255, 153));
        finishQueue_Counter2.setText("Finish");
        finishQueue_Counter2.addActionListener(this::finishQueue_Counter2ActionPerformed);

        finishQueue_Counter3.setBackground(new java.awt.Color(153, 255, 153));
        finishQueue_Counter3.setText("Finish");
        finishQueue_Counter3.addActionListener(this::finishQueue_Counter3ActionPerformed);

        jLabel4.setText("Noqueue");

        jLabel5.setText("Noqueue");

        jLabel6.setText("Noqueue");

        javax.swing.GroupLayout background_counter1_2_3Layout = new javax.swing.GroupLayout(background_counter1_2_3);
        background_counter1_2_3.setLayout(background_counter1_2_3Layout);
        background_counter1_2_3Layout.setHorizontalGroup(
            background_counter1_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_counter1_2_3Layout.createSequentialGroup()
                .addGroup(background_counter1_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background_counter1_2_3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(background_counter1_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(callQueue_Counter1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(finishQueue_Counter1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background_counter1_2_3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addComponent(Divider_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(background_counter1_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background_counter1_2_3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(background_counter1_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(callQueue_Counter2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(finishQueue_Counter2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(background_counter1_2_3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Divider_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(background_counter1_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background_counter1_2_3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(background_counter1_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(callQueue_Counter3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finishQueue_Counter3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(background_counter1_2_3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel6)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        background_counter1_2_3Layout.setVerticalGroup(
            background_counter1_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_counter1_2_3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background_counter1_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(callQueue_Counter1)
                    .addComponent(callQueue_Counter2)
                    .addComponent(callQueue_Counter3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background_counter1_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finishQueue_Counter1)
                    .addComponent(finishQueue_Counter2)
                    .addComponent(finishQueue_Counter3))
                .addGroup(background_counter1_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background_counter1_2_3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(background_counter1_2_3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5))
                    .addGroup(background_counter1_2_3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(background_counter1_2_3Layout.createSequentialGroup()
                .addGroup(background_counter1_2_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Divider_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Divider_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(background_counter1_2_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 470, 100));

        Divider_3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout Divider_3Layout = new javax.swing.GroupLayout(Divider_3);
        Divider_3.setLayout(Divider_3Layout);
        Divider_3Layout.setHorizontalGroup(
            Divider_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Divider_3Layout.setVerticalGroup(
            Divider_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(Divider_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 10, 100));

        background_counter3_4.setBackground(new java.awt.Color(255, 255, 204));
        background_counter3_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        callQueue_counter4.setBackground(new java.awt.Color(153, 255, 255));
        callQueue_counter4.setText("Call Queue");
        callQueue_counter4.addActionListener(this::callQueue_counter4ActionPerformed);

        callQueue_counter5.setBackground(new java.awt.Color(153, 255, 255));
        callQueue_counter5.setText("Call Queue");
        callQueue_counter5.addActionListener(this::callQueue_counter5ActionPerformed);

        finishQueue_counter4.setBackground(new java.awt.Color(153, 255, 153));
        finishQueue_counter4.setText("Finish");
        finishQueue_counter4.addActionListener(this::finishQueue_counter4ActionPerformed);

        finishQueue_counter5.setBackground(new java.awt.Color(153, 255, 153));
        finishQueue_counter5.setText("Finish");
        finishQueue_counter5.addActionListener(this::finishQueue_counter5ActionPerformed);

        jLabel7.setText("Noqueue");

        jLabel8.setText("Noqueue");

        javax.swing.GroupLayout background_counter3_4Layout = new javax.swing.GroupLayout(background_counter3_4);
        background_counter3_4.setLayout(background_counter3_4Layout);
        background_counter3_4Layout.setHorizontalGroup(
            background_counter3_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_counter3_4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background_counter3_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(finishQueue_counter4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(callQueue_counter4, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(background_counter3_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(callQueue_counter5, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(finishQueue_counter5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(background_counter3_4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(58, 58, 58))
        );
        background_counter3_4Layout.setVerticalGroup(
            background_counter3_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background_counter3_4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(background_counter3_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(callQueue_counter4)
                    .addComponent(callQueue_counter5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background_counter3_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishQueue_counter4)
                    .addComponent(finishQueue_counter5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background_counter3_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(background_counter3_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 310, 100));

        loanLabel.setForeground(new java.awt.Color(255, 255, 255));
        loanLabel.setText("Loan");
        getContentPane().add(loanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 50, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Account");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 196, -1, 20));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("queue withdraw-deposit");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setText("queue loan");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 280, 40));

        jPanel3.setBackground(new java.awt.Color(102, 255, 204));

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setText("queuenew account");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(71, 71, 71))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 140, 40));

        bank_Map.setForeground(new java.awt.Color(255, 255, 255));
        bank_Map.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bank_map.jpg"))); // NOI18N
        bank_Map.setMaximumSize(null);
        bank_Map.setMinimumSize(null);
        getContentPane().add(bank_Map, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 1170, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void closeAllCallButtons() {
        callQueue_Counter1.setEnabled(false);
        callQueue_Counter2.setEnabled(false);
        callQueue_Counter3.setEnabled(false);
    }
    private void Withdraw_DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Withdraw_DepositActionPerformed
        withdraw_deposit.enqueue();
        if (!finishQueue_Counter1.isEnabled()) callQueue_Counter1.setEnabled(true);
        if (!finishQueue_Counter2.isEnabled()) callQueue_Counter2.setEnabled(true);
        if (!finishQueue_Counter3.isEnabled()) callQueue_Counter3.setEnabled(true);
    }//GEN-LAST:event_Withdraw_DepositActionPerformed

    private void LoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanActionPerformed
        loan.enqueue();
        if (!finishQueue_counter4.isEnabled()) callQueue_counter4.setEnabled(true);
    }//GEN-LAST:event_LoanActionPerformed

    private void callQueue_Counter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callQueue_Counter1ActionPerformed
        // TODO add your handling code here:
        int ticket = withdraw_deposit.RunningQueue();
        if (ticket != -1) {
            jLabel4.setText("" + ticket);
            callQueue_Counter1.setEnabled(false);
            finishQueue_Counter1.setEnabled(true);
        } else {
            closeAllCallButtons();
        }
    }//GEN-LAST:event_callQueue_Counter1ActionPerformed
  
    private void callQueue_Counter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callQueue_Counter2ActionPerformed
        // TODO add your handling code here:
        int ticket = withdraw_deposit.RunningQueue();
        if (ticket != -1) {
            jLabel5.setText("" + ticket);
            callQueue_Counter2.setEnabled(false);
            finishQueue_Counter2.setEnabled(true);
        } else {
            closeAllCallButtons();
        }  
    }//GEN-LAST:event_callQueue_Counter2ActionPerformed

    private void callQueue_Counter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callQueue_Counter3ActionPerformed
        // TODO add your handling code here:
        int ticket = withdraw_deposit.RunningQueue();
        if (ticket != -1) {
            jLabel6.setText("" + ticket);
            callQueue_Counter3.setEnabled(false);
            finishQueue_Counter3.setEnabled(true);
        } else {
            closeAllCallButtons();
        }   
    }//GEN-LAST:event_callQueue_Counter3ActionPerformed
  
    private void new_AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_AccountActionPerformed
        newacc.enqueue();
        if (!finishQueue_counter5.isEnabled()) callQueue_counter5.setEnabled(true);
    }//GEN-LAST:event_new_AccountActionPerformed

    private void callQueue_counter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callQueue_counter4ActionPerformed
        // TODO add your handling code here:\
        if (!loan.IsEmpty()) {
            int ticket = loan.RunningQueue();
            jLabel7.setText("" + ticket);
            
            callQueue_counter4.setEnabled(false);
            finishQueue_counter4.setEnabled(true);
        }
    }//GEN-LAST:event_callQueue_counter4ActionPerformed
 
    private void callQueue_counter5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callQueue_counter5ActionPerformed
        // TODO add your handling code here:
         if (!newacc.IsEmpty()) {
            int ticket = newacc.RunningQueue();
            jLabel8.setText("" + ticket);
            
            callQueue_counter5.setEnabled(false);
            finishQueue_counter5.setEnabled(true);
        }
    }//GEN-LAST:event_callQueue_counter5ActionPerformed
    
    private void finishQueue_Counter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishQueue_Counter1ActionPerformed
        // TODO add your handling code here:
        if (!withdraw_deposit.IsEmpty()) {
            withdraw_deposit.dequeue(); // 
        }
        jLabel4.setText("No queue");
        finishQueue_Counter1.setEnabled(false);
        
        if (!withdraw_deposit.IsEmpty()) {
            callQueue_Counter1.setEnabled(true);
        }
    }//GEN-LAST:event_finishQueue_Counter1ActionPerformed

    private void finishQueue_Counter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishQueue_Counter2ActionPerformed
        // TODO add your handling code here:
        if (!withdraw_deposit.IsEmpty()) {
            withdraw_deposit.dequeue();
        }
        jLabel5.setText("No queue");
        
        finishQueue_Counter2.setEnabled(false);
        if (!withdraw_deposit.IsEmpty()) {
            callQueue_Counter2.setEnabled(true);
        }
    }//GEN-LAST:event_finishQueue_Counter2ActionPerformed

    private void finishQueue_Counter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishQueue_Counter3ActionPerformed
        // TODO add your handling code here:
        if (!withdraw_deposit.IsEmpty()) {
            withdraw_deposit.dequeue();
        }
        jLabel6.setText("No queue");
        
        finishQueue_Counter3.setEnabled(false);
        if (!withdraw_deposit.IsEmpty()) {
            callQueue_Counter3.setEnabled(true);
        }
    }//GEN-LAST:event_finishQueue_Counter3ActionPerformed

    private void finishQueue_counter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishQueue_counter4ActionPerformed
        // TODO add your handling code here:
        if (!loan.IsEmpty()) {
            loan.dequeue();
        }
        jLabel7.setText("No queue");
        
        finishQueue_counter4.setEnabled(false);
        if (!loan.IsEmpty()) {
            callQueue_counter4.setEnabled(true);
        }
    }//GEN-LAST:event_finishQueue_counter4ActionPerformed

    private void finishQueue_counter5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishQueue_counter5ActionPerformed
        // TODO add your handling code here:
        if (!newacc.IsEmpty()) {
            newacc.dequeue();
        }
        jLabel8.setText("No queue");
        
        finishQueue_counter5.setEnabled(false);
        if (!newacc.IsEmpty()) {
            callQueue_counter5.setEnabled(true);
        }
    }//GEN-LAST:event_finishQueue_counter5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loan.showAll();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        withdraw_deposit.showAll();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        newacc.showAll();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BankJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Divider_1;
    private javax.swing.JPanel Divider_2;
    private javax.swing.JPanel Divider_3;
    private javax.swing.JButton Loan;
    private javax.swing.JLabel NameCounter1;
    private javax.swing.JButton Withdraw_Deposit;
    private javax.swing.JPanel background_counter1_2_3;
    private javax.swing.JPanel background_counter3_4;
    private javax.swing.JLabel bank_Map;
    private javax.swing.JButton callQueue_Counter1;
    private javax.swing.JButton callQueue_Counter2;
    private javax.swing.JButton callQueue_Counter3;
    private javax.swing.JButton callQueue_counter4;
    private javax.swing.JButton callQueue_counter5;
    private javax.swing.JButton finishQueue_Counter1;
    private javax.swing.JButton finishQueue_Counter2;
    private javax.swing.JButton finishQueue_Counter3;
    private javax.swing.JButton finishQueue_counter4;
    private javax.swing.JButton finishQueue_counter5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel loanLabel;
    private javax.swing.JButton new_Account;
    // End of variables declaration//GEN-END:variables
}
